runtime: nodejs22

env_variables:
  VITE_REACT_APP_URL: "http://34.100.144.28"
  VITE_AZURE_MAP_SUB_KEY: "8E6K0YkWGVrUkDzxJqRuCDBfaaXjsKjqfUUx55i0FEfcvZl6NJvCJQQJ99AJACYeBjFPDDZUAAAgAZMP1DYI"
  VITE_GEMINI_API_KEY: "AIzaSyBDQn5W6Zp1ttqbdfMdHwqBs1ZisCAqMP0"
  VITE_FIREBASE_API_KEY: "AIzaSyAZUHq8c_CbrIevZdYzUJnrSkzoNGe3MmE"
  VITE_FIREBASE_AUTH_DOMAIN: "walkez-78deb.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID: "walkez-78deb"
  VITE_FIREBASE_STORAGE_BUCKET: "walkez-78deb.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID: "680115555362"
  VITE_FIREBASE_APP_ID: "1:680115555362:web:65b2f56f981a3f6e440e7b"
  measurementId: "G-1PQSYP3PE8"
  databaseURL: "https://walkez-e3f7e.firebaseio.com"
  GOOGLE_APPLICATION_CREDENTIALS_SERVICE_ACCOUNT: "serviceAccountKey.json"
  GOOGLE_APPLICATION_CREDENTIALS: "serviceAccountKey.json"

handlers:
  - url: /assets
    static_dir: dist/assets

  - url: /(.*\.(js|css|png|jpg|jpeg|gif|ico|svg))
    static_files: dist/\1
    upload: dist/(.*\.(js|css|png|jpg|jpeg|gif|ico|svg))

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
# https://aqueous-ray-453106-k2.el.r.appspot.com/
