version: '3.8'

services:
  web1:
    build: .
    container_name: walkez_backend_1
    ports:
      - "5001:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db

  web2:
    build: .
    container_name: walkez_backend_2
    ports:
      - "5002:5000"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: walkez_db
    environment:
      POSTGRES_USER: walkez
      POSTGRES_PASSWORD: walkez
      POSTGRES_DB: walkez
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: